<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painter SVG en PHP</title>
</head>
<body>
    <header>
        <h1>Painter SVG en PHP</h1>
    </header>
    <main>
        <svg>
            <?=genRectangle(10, 50, 100, 75, 'green', 0.5);?>
        </svg>
    </main>
</body>
</html>