<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painter SVG en PHP</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Painter SVG en PHP</h1>
    </header>
    <main>
        <svg width="1200" height="800">
            <?=genRectangle(10, 50, 100, 75, 'green', 0.5);?>
            <?=genSquare(150, 100, 50, 'crimson', 0.8);?>
            <?=genEllipse(300, 450, 50, 125, 'blue', 1);?>
            <?=genCircle(600, 50, 75, 'orange', 0.4);?>
            <?=genTriangle(520, 240, 160, 400, 54, 110, 'purple', 0.7);?>
        </svg>
    </main>
</body>
</html>