<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire d'ajout d'article</title>
</head>
<body>
    <header>
        <h1>Mon super blog !</h1>
    </header>
    <main>
        <?php include '../templates/' . $template . '.phtml'; ?>
    </main>
</body>
</html>