<section>
    <h2>Les derniers articles</h2>
    <?php // foreach ($articles as $article){ ?>
    <?php foreach ($articles as $article): ?>
        <article>
            <h3><?=htmlspecialchars($article['title']);?></h3>
            <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
            
            <?php if ($article['image']): ?>
                <img src="images/<?=htmlspecialchars($article['image']);?>" alt="">
            <?php endif; ?>

            <p><?=htmlspecialchars($article['abstract'])?htmlspecialchars($article['abstract']):substr(htmlspecialchars($article['content']),0,150) . ' [...]';?> </p>
            <a href="article.php?id=<?=$article['id'];?>">Lire la suite</a>
        </article>
    <?php // } ?>
    <?php endforeach; ?>
</section>
    